### ISSUE TITLE
:repl/set-key-map always reports "Failed to change key map!"

### ISSUE THREAD

**Issue by bkovitz** [bhauman/rebel-readline#142] opened 2018-03-22 20:10 UTC
When I set the key map, e.g. via either of these commands:

    :repl/set-key-map :viins
    :repl/set-key-map :vicmd

it always prints this message:

    Failed to change key map!

In fact, it succeeded, as shown by doing a `:repl/key-bindings`.

(rebel-readline 0.1.1)

**Comment by bhauman** [comment] 2018-03-23 00:47
Duplicate of #139

**Closed by bhauman** 2018-03-23 00:47 UTC
